### ISSUE TITLE
Item loss when Shulker Pack is full

### ISSUE THREAD

**Issue by 994AK** [SirBlobman/ShulkerPackX#2]
When the player's backpack is full，Using ShulkerPackX.
If you drag and drop the item, it will be lost abnormally.
please fix.☹️

**Comment by SirBlobman** [comment]
Do you have a video  or GIF of this issue happening? Also please send the output from these commands:
- `/about SirBlobmanCore`
- `/about ShulkerPackX`

**Comment by MillionthOdin16** [comment]
Believe this was resolved in with a recent update

**Comment by SirBlobman** [comment]
> Believe this was resolved in with a recent update

You are correct, this issue was resolved in v1.4.1
